spring.datasource.url=jdbc:postgresql://localhost:5432/AgendaJava
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

flyway.locations=filesystem:src/main/resources/db/migration

#server.port=8081

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER